"""message

Revision ID: 9b396b31f099
Revises: 
Create Date: 2026-04-18 10:47:20.652754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b396b31f099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoSo',
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('TenCoSo', sa.String(), nullable=False),
    sa.Column('DiaChi', sa.String(), nullable=True),
    sa.Column('SoDienThoai', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('NgayThanhLap', sa.Date(), nullable=True),
    sa.Column('TrangThai', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('MaCoSo')
    )
    op.create_index(op.f('ix_CoSo_MaCoSo'), 'CoSo', ['MaCoSo'], unique=False)
    op.create_table('Khoa',
    sa.Column('MaKhoa', sa.String(), nullable=False),
    sa.Column('TenKhoa', sa.String(), nullable=False),
    sa.Column('MoTa', sa.String(), nullable=True),
    sa.Column('NgayThanhLap', sa.Date(), nullable=True),
    sa.Column('TrangThai', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('MaKhoa'),
    sa.UniqueConstraint('TenKhoa')
    )
    op.create_index(op.f('ix_Khoa_MaKhoa'), 'Khoa', ['MaKhoa'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('NgayTao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=False)
    op.create_table('GiangVien',
    sa.Column('MaGV', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('Ho', sa.String(), nullable=False),
    sa.Column('Ten', sa.String(), nullable=False),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('GioiTinh', sa.String(), nullable=True),
    sa.Column('HocVi', sa.String(), nullable=True),
    sa.Column('HocHam', sa.String(), nullable=True),
    sa.Column('SDT', sa.String(), nullable=True),
    sa.Column('DiaChi', sa.String(), nullable=True),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('MaKhoa', sa.String(), nullable=True),
    sa.Column('TrangThai', sa.String(), nullable=True),
    sa.Column('NgayVaoLam', sa.Date(), nullable=True),
    sa.Column('NgayTao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('MaGV'),
    sa.UniqueConstraint('userId')
    )
    op.create_index(op.f('ix_GiangVien_MaGV'), 'GiangVien', ['MaGV'], unique=False)
    op.create_table('SinhVien',
    sa.Column('MaSV', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('Ho', sa.String(), nullable=False),
    sa.Column('Ten', sa.String(), nullable=False),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('GioiTinh', sa.String(), nullable=True),
    sa.Column('SDT', sa.String(), nullable=True),
    sa.Column('DiaChi', sa.String(), nullable=True),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('MaKhoa', sa.String(), nullable=True),
    sa.Column('TrangThai', sa.String(), nullable=True),
    sa.Column('NgayNhapHoc', sa.Date(), nullable=True),
    sa.Column('NgayTao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('MaSV'),
    sa.UniqueConstraint('userId')
    )
    op.create_index(op.f('ix_SinhVien_MaSV'), 'SinhVien', ['MaSV'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SinhVien_MaSV'), table_name='SinhVien')
    op.drop_table('SinhVien')
    op.drop_index(op.f('ix_GiangVien_MaGV'), table_name='GiangVien')
    op.drop_table('GiangVien')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_Khoa_MaKhoa'), table_name='Khoa')
    op.drop_table('Khoa')
    op.drop_index(op.f('ix_CoSo_MaCoSo'), table_name='CoSo')
    op.drop_table('CoSo')
    # ### end Alembic commands ###
