"""themModelCuaVTuan

Revision ID: 51e0ccf872ae
Revises: 57044f4b5fae
Create Date: 2026-04-18 22:26:00.537341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e0ccf872ae'
down_revision: Union[str, Sequence[str], None] = '57044f4b5fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HocKy',
    sa.Column('MaHocKy', sa.String(), nullable=False),
    sa.Column('NamHoc', sa.String(), nullable=False),
    sa.Column('KySo', sa.Integer(), nullable=False),
    sa.Column('NgayBatDau', sa.Date(), nullable=True),
    sa.Column('NgayKetThuc', sa.Date(), nullable=True),
    sa.Column('TrangThaiHocKy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('MaHocKy')
    )
    op.create_index(op.f('ix_HocKy_MaHocKy'), 'HocKy', ['MaHocKy'], unique=False)
    op.create_table('HocPhan',
    sa.Column('MaHP', sa.String(), nullable=False),
    sa.Column('TenHP', sa.String(), nullable=False),
    sa.Column('SoTinChi', sa.Integer(), nullable=False),
    sa.Column('SoTietLyThuyet', sa.Integer(), nullable=False),
    sa.Column('SoTietThucHanh', sa.Integer(), nullable=False),
    sa.Column('LoaiHocPhan', sa.String(), nullable=False),
    sa.Column('MaKhoa', sa.String(), nullable=False),
    sa.Column('MoTa', sa.String(), nullable=True),
    sa.Column('TrangThai', sa.String(), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MaKhoa'], ['Khoa.MaKhoa'], ),
    sa.PrimaryKeyConstraint('MaHP')
    )
    op.create_index(op.f('ix_HocPhan_MaHP'), 'HocPhan', ['MaHP'], unique=False)
    op.create_table('PhongHoc',
    sa.Column('MaPhong', sa.String(), nullable=False),
    sa.Column('TenPhong', sa.String(), nullable=False),
    sa.Column('ToaNha', sa.String(), nullable=True),
    sa.Column('Tang', sa.Integer(), nullable=True),
    sa.Column('SucChua', sa.Integer(), nullable=False),
    sa.Column('LoaiPhong', sa.String(), nullable=False),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('TrangThai', sa.String(), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MaCoSo'], ['CoSo.MaCoSo'], ),
    sa.PrimaryKeyConstraint('MaPhong')
    )
    op.create_index(op.f('ix_PhongHoc_MaPhong'), 'PhongHoc', ['MaPhong'], unique=False)
    op.create_table('LopHocPhan',
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('MaHP', sa.String(), nullable=False),
    sa.Column('MaHocKy', sa.String(), nullable=False),
    sa.Column('MaCoSo', sa.String(), nullable=False),
    sa.Column('MaGV', sa.String(), nullable=False),
    sa.Column('TenLopHP', sa.String(), nullable=True),
    sa.Column('SiSoToiDa', sa.Integer(), nullable=False),
    sa.Column('SiSoHienTai', sa.Integer(), nullable=False),
    sa.Column('HinhThucHoc', sa.String(), nullable=False),
    sa.Column('TrangThaiLop', sa.String(), nullable=False),
    sa.Column('NgayTao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MaCoSo'], ['CoSo.MaCoSo'], ),
    sa.ForeignKeyConstraint(['MaGV'], ['GiangVien.MaGV'], ),
    sa.ForeignKeyConstraint(['MaHP'], ['HocPhan.MaHP'], ),
    sa.ForeignKeyConstraint(['MaHocKy'], ['HocKy.MaHocKy'], ),
    sa.PrimaryKeyConstraint('MaLopHP')
    )
    op.create_index(op.f('ix_LopHocPhan_MaLopHP'), 'LopHocPhan', ['MaLopHP'], unique=False)
    op.create_table('DangKy',
    sa.Column('MaDangKy', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSV', sa.String(), nullable=False),
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('NgayDangKy', sa.DateTime(), nullable=False),
    sa.Column('TrangThaiDangKy', sa.String(), nullable=False),
    sa.Column('LanDangKy', sa.Integer(), nullable=False),
    sa.Column('GhiChu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['MaLopHP'], ['LopHocPhan.MaLopHP'], ),
    sa.ForeignKeyConstraint(['MaSV'], ['SinhVien.MaSV'], ),
    sa.PrimaryKeyConstraint('MaDangKy'),
    sa.UniqueConstraint('MaSV', 'MaLopHP', name='uq_dk_sv_lophp')
    )
    op.create_index(op.f('ix_DangKy_MaDangKy'), 'DangKy', ['MaDangKy'], unique=False)
    op.create_table('LichHoc',
    sa.Column('MaLich', sa.String(), nullable=False),
    sa.Column('MaLopHP', sa.String(), nullable=False),
    sa.Column('MaPhong', sa.String(), nullable=False),
    sa.Column('ThuTrongTuan', sa.Integer(), nullable=False),
    sa.Column('TietBatDau', sa.Integer(), nullable=False),
    sa.Column('SoTiet', sa.Integer(), nullable=False),
    sa.Column('NgayBatDau', sa.Date(), nullable=True),
    sa.Column('NgayKetThuc', sa.Date(), nullable=True),
    sa.Column('GhiChu', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['MaLopHP'], ['LopHocPhan.MaLopHP'], ),
    sa.ForeignKeyConstraint(['MaPhong'], ['PhongHoc.MaPhong'], ),
    sa.PrimaryKeyConstraint('MaLich')
    )
    op.create_index(op.f('ix_LichHoc_MaLich'), 'LichHoc', ['MaLich'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LichHoc_MaLich'), table_name='LichHoc')
    op.drop_table('LichHoc')
    op.drop_index(op.f('ix_DangKy_MaDangKy'), table_name='DangKy')
    op.drop_table('DangKy')
    op.drop_index(op.f('ix_LopHocPhan_MaLopHP'), table_name='LopHocPhan')
    op.drop_table('LopHocPhan')
    op.drop_index(op.f('ix_PhongHoc_MaPhong'), table_name='PhongHoc')
    op.drop_table('PhongHoc')
    op.drop_index(op.f('ix_HocPhan_MaHP'), table_name='HocPhan')
    op.drop_table('HocPhan')
    op.drop_index(op.f('ix_HocKy_MaHocKy'), table_name='HocKy')
    op.drop_table('HocKy')
    # ### end Alembic commands ###
