-- Check row counts across all sites
\echo '=== HADONG ==='
SELECT 'HADONG' AS site, 'SinhVien' AS tbl, COUNT(*) AS cnt FROM "SinhVien"
UNION ALL SELECT 'HADONG','GiangVien',COUNT(*) FROM "GiangVien"
UNION ALL SELECT 'HADONG','PhongHoc',COUNT(*) FROM "PhongHoc"
UNION ALL SELECT 'HADONG','LopHocPhan',COUNT(*) FROM "LopHocPhan"
UNION ALL SELECT 'HADONG','LichHoc',COUNT(*) FROM "LichHoc"
UNION ALL SELECT 'HADONG','DangKy',COUNT(*) FROM "DangKy"
UNION ALL SELECT 'HADONG','CoSo',COUNT(*) FROM "CoSo"
UNION ALL SELECT 'HADONG','users',COUNT(*) FROM "users"
UNION ALL SELECT 'HADONG','Khoa',COUNT(*) FROM "Khoa"
UNION ALL SELECT 'HADONG','HocPhan',COUNT(*) FROM "HocPhan"
UNION ALL SELECT 'HADONG','HocKy',COUNT(*) FROM "HocKy"
UNION ALL SELECT 'HADONG','TienQuyet',COUNT(*) FROM "TienQuyet";

\echo '=== NGOCTRUC ==='
SELECT 'NGOCTRUC' AS site, 'SinhVien' AS tbl, COUNT(*) AS cnt FROM "SinhVien"
UNION ALL SELECT 'NGOCTRUC','GiangVien',COUNT(*) FROM "GiangVien"
UNION ALL SELECT 'NGOCTRUC','PhongHoc',COUNT(*) FROM "PhongHoc"
UNION ALL SELECT 'NGOCTRUC','LopHocPhan',COUNT(*) FROM "LopHocPhan"
UNION ALL SELECT 'NGOCTRUC','LichHoc',COUNT(*) FROM "LichHoc"
UNION ALL SELECT 'NGOCTRUC','DangKy',COUNT(*) FROM "DangKy";

\echo '=== HOALAC ==='
SELECT 'HOALAC' AS site, 'SinhVien' AS tbl, COUNT(*) AS cnt FROM "SinhVien"
UNION ALL SELECT 'HOALAC','GiangVien',COUNT(*) FROM "GiangVien"
UNION ALL SELECT 'HOALAC','PhongHoc',COUNT(*) FROM "PhongHoc"
UNION ALL SELECT 'HOALAC','LopHocPhan',COUNT(*) FROM "LopHocPhan"
UNION ALL SELECT 'HOALAC','LichHoc',COUNT(*) FROM "LichHoc"
UNION ALL SELECT 'HOALAC','DangKy',COUNT(*) FROM "DangKy";

\echo '=== CENTRALIZED ==='
SELECT 'CENTRALIZED' AS site, 'SinhVien' AS tbl, COUNT(*) AS cnt FROM "SinhVien"
UNION ALL SELECT 'CENTRALIZED','GiangVien',COUNT(*) FROM "GiangVien"
UNION ALL SELECT 'CENTRALIZED','PhongHoc',COUNT(*) FROM "PhongHoc"
UNION ALL SELECT 'CENTRALIZED','LopHocPhan',COUNT(*) FROM "LopHocPhan"
UNION ALL SELECT 'CENTRALIZED','LichHoc',COUNT(*) FROM "LichHoc"
UNION ALL SELECT 'CENTRALIZED','DangKy',COUNT(*) FROM "DangKy"
UNION ALL SELECT 'CENTRALIZED','CoSo',COUNT(*) FROM "CoSo"
UNION ALL SELECT 'CENTRALIZED','users',COUNT(*) FROM "users"
UNION ALL SELECT 'CENTRALIZED','Khoa',COUNT(*) FROM "Khoa"
UNION ALL SELECT 'CENTRALIZED','HocPhan',COUNT(*) FROM "HocPhan"
UNION ALL SELECT 'CENTRALIZED','HocKy',COUNT(*) FROM "HocKy"
UNION ALL SELECT 'CENTRALIZED','TienQuyet',COUNT(*) FROM "TienQuyet";
